apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactcicd
  template:
    metadata:
      labels:
        app: reactcicd
    spec:
      containers:
      - name: reactcicd
        image: hanaac22/reactcicd:4ec991887e39ceb8193d658ec9398e7d25d738aa
        ports:
        - containerPort: 80
