apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactcicd
  template:
    metadata:
      labels:
        app: reactcicd
    spec:
      containers:
      - name: reactcicd
        image: hanaac22/reactcicd:a5dfc2648551f61ef83b05f3d7537b4c337f5dbe
        ports:
        - containerPort: 80
